### ISSUE TITLE
Setting gpt-2 as the transformer decoder

### ISSUE THREAD

**Issue by ghost** [asyml/texar#137]
Hi,

In the transoformer example, I replaced the decoder with the gpt2 decoder as described in the conditional generation example.

I get the following error:

```
python transformer_gpt.py --run_mode=train_and_evaluate --config_model=config_model --config_data=config_iwslt15
train data size:183011

logging file is saved in: %s ./outputs/logging.txt
Traceback (most recent call last):
  File "/home/nv/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1589, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 680 and 512 for 'transformer_decoder_1/add' (op: 'Add') with input shapes: [?,?,680], [1,?,512].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transformer_gpt.py", line 285, in <module>
    main()
  File "transformer_gpt.py", line 113, in main
    mode=tf.estimator.ModeKeys.TRAIN
  File "/home/text_sum/texar/texar/module_base.py", line 116, in __call__
    return self._template(*args, **kwargs)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 419, in __call__
    return self._call_func(args, kwargs)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 370, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/text_sum/texar/texar/modules/decoders/transformer_decoders.py", line 528, in _build
    inputs = target_inputs + pos_embeds
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 847, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1756, in __init__
    control_input_ops)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1592, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 680 and 512 for 'transformer_decoder_1/add' (op: 'Add') with input shapes: [?,?,680], [1,?,512].

originally defined at:
  File "transformer_gpt.py", line 104, in main
    decoder = TransformerDecoder(embedding=tgt_embedding, hparams=gpt_config.decoder)
  File "/home/text_sum/texar/texar/modules/decoders/transformer_decoders.py", line 86, in __init__
    ModuleBase.__init__(self, hparams)
  File "/home/text_sum/texar/texar/module_base.py", line 73, in __init__
    create_scope_now_=True)
  File "/home/anaconda2/envs/june/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)
```

**Comment by ZhitingHu** [comment]
```
File "/home/text_sum/texar/texar/modules/decoders/transformer_decoders.py", line 528, in _build
    inputs = target_inputs + pos_embeds
```

You would need to config the embedding dimensions properly

**Comment by nvidiaman** [comment]
@ZhitingHu i tried embedding dimensions = 768, as in the gpt-2 model and still get the same error. the config for gpt-2 has only one embedding parameter. Any other parameter is required to be set?

**Comment by ZhitingHu** [comment]
Ok. It looks you're using an old version of Texar. Can you try out the latest one (v0.2.1) in the master branch?

**Comment by nvidiaman** [comment]
@ZhitingHu thanks, I switched to version 0.21-unreleased from github in the transformer main I try to do:

is to replace the Tranformer decoder with the gpt-2 decoder config:

`decoder = TransformerDecoder(vocab_size=vocab_size, output_layer=_output_w, hparams=gpt_config.decoder)`

Still I get the error:
`
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 512 and 768 for 'transformer_decoder_1/layer_0/self_attention/add' (op: 'Add') with input shapes: [?,?,512], [?,?,768].`

Even though gpt_config is the config used for gpt-2 with the embedding dimension 768.

Please let me know if I missed any step?

**Comment by ZhitingHu** [comment]
The error is already different from the previous one.

Is the encoder hidden size the same as the decoder hidden size? I guess 768 is the encoder hidden size and 512 the decoder. They must be the same
