### ISSUE TITLE
Text Style Transfer: TF error when trying to reproduce with different text data

### ISSUE THREAD

**Issue by rkingery** [asyml/texar#145]
Hello, I am trying to reproduce the text style transfer example you have, but on different data. I've managed to format my files to match the config and modified the config accordingly to read it in. This includes different train, dev, test data as well as new vocab. Other than this I haven't modified anything in your original code. However, when trying to run the code I get the following TF error. Any ideas what could be causing this and how to fix it? Thanks.

```
Traceback (most recent call last):
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1:0) = ] [64 119] [y (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice:0) = ] [64 21]
	 [[{{node sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert}} = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/All/_259, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_0, attention_rnn_decoder_6/decoder/AttentionWrapperZeroState/assert_equal/Assert/Assert/data_1, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_2, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1/_261, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_4, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/_263)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 191, in <module>
    tf.app.run(main=_main)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 177, in _main
    _train_epoch(sess, gamma_, lambda_g_, epoch)
  File "main.py", line 93, in _train_epoch
    vals_g = sess.run(model.fetches_train_g, feed_dict=feed_dict)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1:0) = ] [64 119] [y (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice:0) = ] [64 21]
	 [[node sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert (defined at /home/ryankingery/Repos/texar/texar/losses/mle_losses.py:196)  = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/All/_259, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_0, attention_rnn_decoder_6/decoder/AttentionWrapperZeroState/assert_equal/Assert/Assert/data_1, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_2, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1/_261, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_4, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/_263)]]

Caused by op 'sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert', defined at:
  File "main.py", line 191, in <module>
    tf.app.run(main=_main)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 69, in _main
    model = CtrlGenModel(batch, vocab, gamma, lambda_g, config.model)
  File "/home/ryankingery/Repos/texar/examples/text_style_transfer/ctrl_gen_model.py", line 38, in __init__
    self._build_model(inputs, vocab, gamma, lambda_g)
  File "/home/ryankingery/Repos/texar/examples/text_style_transfer/ctrl_gen_model.py", line 83, in _build_model
    sum_over_timesteps=False)
  File "/home/ryankingery/Repos/texar/texar/losses/mle_losses.py", line 196, in sequence_sparse_softmax_cross_entropy
    labels=labels, logits=logits)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2062, in sparse_softmax_cross_entropy_with_logits
    array_ops.shape(logits)[:-1]))
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 390, in assert_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 159, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 52, in _assert
    name=name)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ryankingery/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): assertion failed: [] [Condition x == y did not hold element-wise:] [x (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1:0) = ] [64 119] [y (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice:0) = ] [64 21]
	 [[node sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert (defined at /home/ryankingery/Repos/texar/texar/losses/mle_losses.py:196)  = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/All/_259, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_0, attention_rnn_decoder_6/decoder/AttentionWrapperZeroState/assert_equal/Assert/Assert/data_1, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_2, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1/_261, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert/data_4, sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice/_263)]]
```

**Comment by ZhitingHu** [comment]
Hi, have you tried the default dataset? did it work on your side?

**Comment by ZhitingHu** [comment]
The error should be because of the config `max_decoding_length_*`, which are set to 20/21 now: https://github.com/asyml/texar/blob/master/examples/text_style_transfer/config.py#L85-L86

Your text is longer (>= 119). You may want to config `max_decoding_length_*` accordingly

**Comment by rkingery** [comment]
That seemed to fix it. Also had issues with OOM on the GPU (single P-100), but mostly fixed that I think by decreasing the batch size and sequence lengths. Will see how training goes. Thanks.
