### ISSUE TITLE
Bugs When Using text_style_transfer on My Own dataset

### ISSUE THREAD

**Issue by XinDongol** [asyml/texar#210]
I am running `example/text_style_transfer` and get an error like the following. 

Could you please provide some hint which may be helpful for debugging?

Thanks a lot. 

```
Traceback (most recent call last):
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1:0) = ] [64 31] [y (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice:0) = ] [64 21]
         [[{{node sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 191, in <module>
    tf.app.run(main=_main)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/n/home05/simonx/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/n/home05/simonx/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 177, in _main
    _train_epoch(sess, gamma_, lambda_g_, epoch)
  File "main.py", line 93, in _train_epoch
    vals_g = sess.run(model.fetches_train_g, feed_dict=feed_dict)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [] [Condition x == y did not hold element-wise:] [x (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/Shape_1:0) = ] [64 31] [y (sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/strided_slice:0) = ] [64 21]
         [[node sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert (defined at /n/home05/simonx/anaconda3/lib/python3.6/site-packages/texar/tf/losses/mle_losses.py:196) ]]

Original stack trace for 'sequence_sparse_softmax_cross_entropy/SparseSoftmaxCrossEntropyWithLogits/assert_equal/Assert/Assert':
  File "main.py", line 191, in <module>
    tf.app.run(main=_main)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/n/home05/simonx/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/n/home05/simonx/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 69, in _main
    model = CtrlGenModel(batch, vocab, gamma, lambda_g, config.model)
  File "/n/scratchlfs/kung_lab/xin/xin/StyleTrans/style_transformer/hu_style/ctrl_gen_model.py", line 38, in __init__
    self._build_model(inputs, vocab, gamma, lambda_g)
  File "/n/scratchlfs/kung_lab/xin/xin/StyleTrans/style_transformer/hu_style/ctrl_gen_model.py", line 83, in _build_model
    sum_over_timesteps=False)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/texar/tf/losses/mle_losses.py", line 196, in sequence_sparse_softmax_cross_entropy
    labels=labels, logits=logits)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 3355, in sparse_softmax_cross_entropy_with_logits
    array_ops.shape(logits)[:-1]))
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py", line 557, in assert_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 193, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 163, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 74, in _assert
    name=name)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/n/home05/simonx/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by ZhitingHu** [comment]
It's probably because `labels` and `logits` [here](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/ctrl_gen_model.py#L78) are of different lengths.

Did you use a different dataset? Have you set "max_decoding_length" correctly? (Refer to https://github.com/asyml/texar/issues/27 or https://github.com/asyml/texar/issues/145)

**Comment by XinDongol** [comment]
Thanks @ZhitingHu .

Fixed this bug by setting `max_decoding_lenght_train/infer` properly.
