### ISSUE TITLE
Add pre-trained GPT2 model

### ISSUE THREAD

**Issue by gpengzhi** [asyml/texar#220]

**Comment by 1024er** [comment]
python vae_train.py --config config_lstm_ptb.py

Traceback (most recent call last):
  File "vae_train.py", line 42, in <module>
    import texar.tf as tx
  File "/usr/local/lib/python3.5/site-packages/texar/tf/__init__.py", line 41, in <module>
    from texar.tf import data
  File "/usr/local/lib/python3.5/site-packages/texar/tf/data/__init__.py", line 25, in <module>
    from texar.tf.data.tokenizers import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/data/tokenizers/__init__.py", line 18, in <module>
    from texar.tf.data.tokenizers.bert_tokenizer import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/data/tokenizers/bert_tokenizer.py", line 25, in <module>
    from texar.tf.modules.pretrained.bert import PretrainedBERTMixin
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/__init__.py", line 24, in <module>
    from texar.tf.modules.classifiers import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/classifiers/__init__.py", line 24, in <module>
    from texar.tf.modules.classifiers.conv_classifiers import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/classifiers/conv_classifiers.py", line 28, in <module>
    from texar.tf.modules.encoders.conv_encoders import Conv1DEncoder
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/encoders/__init__.py", line 25, in <module>
    from texar.tf.modules.encoders.bert_encoder import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/encoders/bert_encoder.py", line 29, in <module>
    from texar.tf.modules.pretrained.bert import PretrainedBERTMixin
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/pretrained/__init__.py", line 20, in <module>
    from texar.tf.modules.pretrained.gpt2 import *
  File "/usr/local/lib/python3.5/site-packages/texar/tf/modules/pretrained/gpt2.py", line 70
    'gpt2-small': [_GPT2_PATH + f"124M/{file}"
                                             ^
SyntaxError: invalid syntax
------
python 3.5.3 env

**Comment by gpengzhi** [comment]
I think this is a python version related issue. f-strings is introduced in python 3.6. Texar>0.2.3 requires Python 3.6 or 3.7. To use with older Python versions, please use Texar<=0.2.3
