### ISSUE TITLE
Potential bug in MT Transformer example

### ISSUE THREAD

**Issue by mgupta1410** [asyml/texar#235]
On running sh preprocess_data.sh bpe en de for the MT Transformer example - https://github.com/asyml/texar/tree/master/examples/transformer, I am getting the following error (truncated some successful lines for brevity) -

```
sh preprocess_data.sh bpe en de
Writing to data/en_de_temp//cache. To change this, set the OUTPUT_DIR_CACHE environment variable.
Downloading files
....
Extracting all files...
......
scripts/wmt14_en_de.sh: 88: scripts/wmt14_en_de.sh: cannot create data/en_de_temp//cache/train.en: Directory nonexistent
scripts/wmt14_en_de.sh: 94: scripts/wmt14_en_de.sh: cannot create data/en_de_temp//cache/train.de: Directory nonexistent
Cloning moses for data processing
........
Tokenizing data/en_de_temp//cache/newstest2009.de...
..........
Cleaning data/en_de_temp//cache/train.tok...
clean-corpus.perl: processing data/en_de_temp//cache/train.tok.de & .en to data/en_de_temp//cache/train.tok.clean, cutoff 1-80, ratio 9
Error: data/en_de_temp//cache/train.tok.de does not exist at data/en_de_temp//cache/mosesdecoder/scripts/training/clean-corpus-n.perl line 58.
Output dir = temp/run_en_de_bpe
Step 1a: Preprocess inputs
Learning Byte Pairwise on source and target combined
cat: /home/mansi.gupta/texar/examples/transformer/data/en_de/train.en: No such file or directory
cat: /home/mansi.gupta/texar/examples/transformer/data/en_de/train.de: No such file or directory
Traceback (most recent call last):
  File "/home/mansi.gupta/texar/examples/transformer/../../bin/utils//learn_bpe", line 252, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "/home/mansi.gupta/texar/examples/transformer/../../bin/utils//learn_bpe", line 203, in main
    threshold = max(stats.values()) / 10
ValueError: max() arg is an empty sequence
preprocess_data.sh: 68: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/train.en: No such file
preprocess_data.sh: 69: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/dev.en: No such file
preprocess_data.sh: 70: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/test.en: No such file
preprocess_data.sh: 71: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/train.de: No such file
preprocess_data.sh: 72: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/dev.de: No such file
preprocess_data.sh: 73: preprocess_data.sh: cannot open /home/mansi.gupta/texar/examples/transformer/data/en_de/test.de: No such file
cp: cannot stat '/home/mansi.gupta/texar/examples/transformer/data/en_de/test.de': No such file or directory
{
    "source_vocab": 40000,
    "target_vocab": 40000,
    "tok": false,
    "max_seq_length": 70,
    "pre_encoding": "bpe",
    "src": "en.bpe",
    "tgt": "de.bpe",
    "input_dir": "temp/run_en_de_bpe/data",
    "save_data": "processed.",
    "input": "temp/run_en_de_bpe/data",
    "source_train": "train.en.bpe",
    "target_train": "train.de.bpe",
    "source_valid": "valid.en.bpe",
    "target_valid": "valid.de.bpe",
    "source_test": "test.en.bpe",
    "target_test": "test.de.bpe"
}
Traceback (most recent call last):
  File "/home/mansi.gupta/texar/examples/transformer/utils/preprocess.py", line 144, in <module>
    src_cntr = count_words(source_path, args.source_vocab, args.tok)
  File "/home/mansi.gupta/texar/examples/transformer/utils/preprocess.py", line 69, in count_words
    for words in read_file(path, tok):
  File "/home/mansi.gupta/texar/examples/transformer/utils/preprocess.py", line 60, in read_file
    with open_file(path) as f:
  File "/home/mansi.gupta/texar/examples/transformer/utils/preprocess.py", line 55, in open_file
    return open(path, encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'temp/run_en_de_bpe/data/train.en.bpe'
```

Related to - https://github.com/asyml/texar-pytorch/issues/192

**Comment by ZhitingHu** [comment]
Does the solution to asyml/texar-pytorch#192 solve this issue?

**Comment by mgupta1410** [comment]
@ZhitingHu yeah, asyml/texar-pytorch#192 solves this issue. Applied it locally and checked.

**Comment by gpengzhi** [comment]
Cool. I will fix it accordingly.
