### ISSUE TITLE
ImportError: No module named 'texar.tf'

### ISSUE THREAD

**Issue by TWJ718925** [asyml/texar#279]
There is an error when using tx.modules.TransformerEncoder to pass hparams!How to deal with it?

Traceback (most recent call last):
  File "/home/twjing/PycharmProjects/infilling/Text_Infilling-master/seq2seq.py", line 34, in <module>
    import seq2seq_hyperparams
  File "/home/twjing/PycharmProjects/infilling/Text_Infilling-master/seq2seq_hyperparams.py", line 10, in <module>
    from texar.tf.modules import default_transformer_poswise_net_hparams
ImportError: No module named 'texar.tf'

**Comment by ZhitingHu** [comment]
Your texar is probably not installed correctly.  Did you follow the steps here: https://github.com/asyml/texar#installation
