### ISSUE TITLE
Question about the installation about the version 0.2.1

### ISSUE THREAD

**Issue by xinli2008** [asyml/texar#299]
Hello, I am trying to reproduce a project , there say i need to install texar 0.2.1,Because the texar 0.2.1 is saved there .
[https://github.com/fabrahman/Emo-Aware-Storytelling/tree/master/third_party/texar](url)
And i run -> pip install .       And the system show Successfully installed texar-0.2.1 ;
But when i run python to enter python environment and run import texar to test if it is successfully downloaded.
Something happened!
It says :>>> import texar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/__init__.py", line 29, in <module>
    from texar import modules
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/modules/__init__.py", line 24, in <module>
    from texar.modules.networks import *
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/modules/networks/__init__.py", line 24, in <module>
    from texar.modules.networks.network_base import *
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/modules/networks/network_base.py", line 26, in <module>
    from texar.core.layers import get_layer
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/core/__init__.py", line 24, in <module>
    from texar.core.layers import *
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/texar/core/layers.py", line 25, in <module>
    import tensorflow.contrib.rnn as rnn
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 38, in <module>
    from tensorflow.contrib import cloud
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/tensorflow/contrib/cloud/__init__.py", line 24, in <module>
    from tensorflow.contrib.cloud.python.ops.bigquery_reader_ops import *
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/tensorflow/contrib/cloud/python/ops/bigquery_reader_ops.py", line 21, in <module>
    from tensorflow.contrib.cloud.python.ops import gen_bigquery_reader_ops
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/tensorflow/contrib/cloud/python/ops/gen_bigquery_reader_ops.py", line 307, in <module>
    _op_def_lib = _InitOpDefLibrary(b"\n\355\001\n\016BigQueryReader\032\024\n\rreader_handle\030\007\200\001\001\"\027\n\tcontainer\022\006string\032\002\022\000\"\031\n\013shared_name\022\006string\032\002\022\000\"\024\n\nproject_id\022\006string\"\024\n\ndataset_id\022\006string\"\022\n\010table_id\022\006string\"\027\n\007columns\022\014list(string)\"\027\n\020timestamp_millis\022\003int\"\034\n\016test_end_point\022\006string\032\002\022\000\210\001\001\n\331\001\n GenerateBigQueryReaderPartitions\032\016\n\npartitions\030\007\"\024\n\nproject_id\022\006string\"\024\n\ndataset_id\022\006string\"\022\n\010table_id\022\006string\"\027\n\007columns\022\014list(string)\"\027\n\020timestamp_millis\022\003int\"\025\n\016num_partitions\022\003int\"\034\n\016test_end_point\022\006string\032\002\022\000")
  File "/home/lixin/enter/envs/lx03/lib/python3.6/site-packages/tensorflow/contrib/cloud/python/ops/gen_bigquery_reader_ops.py", line 215, in _InitOpDefLibrary
    _op_def_registry.register_op_list(op_list)
AttributeError: module 'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'

Can you give me some useful advide ,I am so sorry to bother you ! @ZhitingHu

**Comment by shaoniana1997** [comment]
Sorry,the url above is wrong ,here is the right url;
[https://github.com/fabrahman/Emo-Aware-Storytelling/tree/master/third_party/texar](url)

**Comment by shaoniana1997** [comment]
https://github.com/fabrahman/Emo-Aware-Storytelling/tree/master/third_party/texar

**Comment by xinli2008** [comment]
Sorry,the url above is wrong ! Here is the right url；
https://github.com/fabrahman/Emo-Aware-Storytelling/tree/master/third_party/texar
