### ISSUE TITLE
Problem with the prepare_data.py  in  text_style_transfer

### ISSUE THREAD

**Issue by ha-lins** [asyml/texar#67]
Hi!
I'm learning the example "text_style_transfer".When I run the prepare_data.py,i got the problem:
//
_`Traceback (most recent call last):
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fdefd25a630>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1HaUKEYDBEk6GlJGmXwqYteB-4rS9q8Lg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdefd25a630>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prepare_data.py", line 35, in <module>
    main()
  File "prepare_data.py", line 32, in main
    prepare_data()
  File "prepare_data.py", line 27, in prepare_data
    extract=True)
  File "/data/linshuai/texar/texar/data/data_utils.py", line 90, in maybe_download
    filepath = _download_from_google_drive(url, filename, path)
  File "/data/linshuai/texar/texar/data/data_utils.py", line 143, in _download_from_google_drive
    response = sess.get(gurl, params={'id': file_id}, stream=True)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/linshuai/anaconda3/envs/tf018/lib/python3.5/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1HaUKEYDBEk6GlJGmXwqYteB-4rS9q8Lg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdefd25a630>: Failed to establish a new connection: [Errno 111] Connection refused',))
`
//
could you tell me how to solve this problem?Thanks a lot!

**Comment by ZhitingHu** [comment]
The error occurs when downloading data from google drive [here](https://github.com/asyml/texar/blob/master/examples/text_style_transfer/prepare_data.py#L23).

Please make sure your server has network connection.

Or, you may manually download the data from `https://drive.google.com/file/d/1HaUKEYDBEk6GlJGmXwqYteB-4rS9q8Lg/view?usp=sharing` and put it under `examples/text_style_transfer`, and run `prepare_data.py` again
